######################################
# Server properties
######################################
server:
  servlet:
    context-path: /users-service

######################################
# Spring application properties
######################################
spring:
  profiles: 
    active: ${app.profile:testcase}
  application:
    name: userservice
#################################################################
# = Actuator Parameters
#################################################################
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,metrics,refresh,bus-refresh
        
################################################################
# = Parametri Sicurezza JWT 
#################################################################
token-config:
    uri: /auth
    refresh: /refresh
    header: Authorization
    prefix: Bearer 
    expiration: 86400
    secret: 123_Stella