######################################
# Server properties
######################################
server:
  servlet:    context-path: /SpringRestApiDemo

######################################
# Spring application properties
######################################
spring:
  profiles: 
    active: ${app.profile}
  application:
    name: SpringRestApiDemo
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true

# ==============================================================
# = Actuator Parameters
# ==============================================================
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,metrics,refresh,bus-refresh
        