# ==============================================================
# = Config Server need authentication for work
# ==============================================================
server:
 servlet:
   context-path: /ConfigServerRestApi
   
spring:
 application:
    name: ConfigServerRestApi
 
# ==============================================================
# = Cloud Parameters
# ============================================================== 
 cloud:
   config:
     server:
        git:
          uri: ${repository:http://localhost:8089/rest-api-demo-config.git}

# ==============================================================
# = Actuator Parameters
# ==============================================================
management:
  endpoint:
    health:
      show-details: WHEN_AUTHORIZED
  endpoints:
    web:
      exposure:
        include: health,info,metrics,shutdown

# ==============================================================
# = Actuator Info
# ==============================================================
info:
  author:
    name: "Luciano Grippa"
  application:
    name-app: "Config-Server for Rest api demo"
    profile: "FILE"
        
# ==============================================================
# = Logs Parameters
# ==============================================================        
logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.security: DEBUG
    
# ==============================================================
# = Security Parameters
# ============================================================== 
basic:
  security:
    userpwd: 'appconfiguration-devel'
    adminpwd: 'ab34h2537cc302398232gdf'  







