version: '3.3'
networks: 
  ntrestapi:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.22.0.0/24
        
services:
  tomcatapp:
    build: ./tomcat
    container_name: tomcatapp
    networks: 
      ntrestapi:
        ipv4_address: 192.22.0.2
    ports:
    - 8080:8080
    - 8787:8787
    volumes:
    - ./tomcat/webapps:/opt/tomcat/webapps
    - ./tomcat/configuration/webapps:/opt/tomcat/configuration/webapps
    - ./tomcat/conf:/opt/tomcat/conf
    - ./tomcat/logs:/opt/tomcat/logs
    depends_on:
    - appdb
    links:
    - appdb:tomcatdbhost
  appdb:
    build:
      context: ./mysql
    networks: 
      ntrestapi:
        ipv4_address: 192.22.0.3
    image: tomcat-db
    container_name: tomcat-db
    # volumes:
    #   - ./data:/var/lib/mysql/restapidemo
    environment:
      TZ: Europe/Rome
      MYSQL_IP: ::1
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_DATABASE: restapidemo
      MYSQL_USER: user
      MYSQL_PASSWORD: ma45lata
      MYSQL_ROOT_PASSWORD: kj7£fiU
    ports:
    - 3306:3306
    
  phpmyadmin:
    depends_on:
    - appdb
    networks: 
      ntrestapi:
        ipv4_address: 192.22.0.4
    image: phpmyadmin/phpmyadmin
    container_name: myadmin-tomcat
    restart: always
    environment:
      PMA_ARBITRARY: 1
    links:
    - appdb:tomcatdb
    ports:
    - 8883:80