version: '3.3'
networks: 
  ntrestapi:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.22.0.0/24
        
services:

  #######################################
  # WILDFLY
  ########################################
  wildfly:
    build: ./wildfly
    container_name: wildfly
    environment:
      configserverurl: "http://192.22.0.7:8181/ConfigServerRestApi"
    networks: 
      ntrestapi:
        ipv4_address: 192.22.0.2
    ports:
    - 8080:8080
    - 9990:9990
    - 9999:9999
    - 8794:8787
    volumes:
    - ./wildfly/standalone/deployments:/opt/jboss/wildfly/standalone/deployments
    - ./wildfly/standalone/configuration/webapps:/opt/jboss/wildfly/standalone/configuration/webapps
    - ./wildfly/standalone/log:/opt/jboss/wildfly/standalone/log
    - ./wildfly/standalone/lib:/opt/jboss/wildfly/standalone/lib
    depends_on:
    - appdb
    links:
    - appdb:wildflydbhost
  
  #######################################
  # TOMCAT
  ########################################
  tomcatapp:
      build: ./tomcat
      container_name: tomcatapp
      networks: 
        ntrestapi:
          ipv4_address: 192.22.0.5
      ports:
      - 8081:8080
      - 8787:8787
      volumes:
      - ./tomcat/webapps:/opt/tomcat/webapps
      - ./tomcat/configuration/webapps:/opt/tomcat/configuration/webapps
      - ./tomcat/conf:/opt/tomcat/conf
      - ./tomcat/logs:/opt/tomcat/logs
      depends_on:
      - appdb
      links:
      - appdb:tomcatdbhost

  #######################################
  # MYSQL
  ########################################
  appdb:
    build:
      context: ./mysql
    networks: 
      ntrestapi:
        ipv4_address: 192.22.0.3
    image: wildfly-db
    container_name: wildfly-db
    environment:
      TZ: Europe/Rome
      MYSQL_IP: ::1
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_DATABASE: restapidemo
      MYSQL_USER: user
      MYSQL_PASSWORD: ma45lata
      MYSQL_ROOT_PASSWORD: kj7£fiU
    ports:
    - 3306:3306
  
  #######################################
  # PHP MY ADMIN
  ########################################
  phpmyadmin:
    depends_on:
    - appdb
    networks: 
      ntrestapi:
        ipv4_address: 192.22.0.4
    image: phpmyadmin/phpmyadmin
    container_name: myadmin-wildfly
    restart: always
    environment:
      PMA_ARBITRARY: 1
    links:
    - appdb:wildflydb
    ports:
    - 8883:80

  #######################################
  # GIT SERVER
  ########################################
  git-server:
    build: ./gitserver
    container_name: gitserver
    image: gitserver
    networks: 
      ntrestapi:
        ipv4_address: 192.22.0.6
    restart: always
    ports:
      - 8089:80
    volumes:
      - ./gitserver/repos/rest-api-demo-config.git:/var/www/git/rest-api-demo-config.git
  #######################################
  # Spring boot starter
  ########################################
  springboot:
    build: ./springboot
    container_name: springboot
    image: springboot
    networks: 
      ntrestapi:
        ipv4_address: 192.22.0.7
    restart: always
    ports:
      - 8181:8181
      - 8182:8182
      - 8183:8183
      - 8184:8184
      - 8185:8185
      - 8186:8186
      - 8187:8187
      - 8188:8188
      - 8189:8189
      - 8190:8190
    volumes:
      - ./springboot/env:/root/app/env
      - ./springboot/exec:/root/app/exec
      - ./springboot/log:/root/app/log
    depends_on:
      - appdb
    links:
      - appdb:springbootdb    
      
      
      
      
  