version: '3.3'
networks: 
  ntrestapi:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.22.0.0/24
        
services:
  wildfly:
    build: ./wildfly
    container_name: wildfly
    networks: 
      ntrestapi:
        ipv4_address: 192.22.0.2
    ports:
    - 8080:8080
    - 9990:9990
    - 9999:9999
    - 8787:8787
    volumes:
    - ./wildfly/standalone/deployments:/opt/jboss/wildfly/standalone/deployments
    - ./wildfly/standalone/configuration/webapps:/opt/jboss/wildfly/standalone/configuration/webapps
    - ./wildfly/standalone/log:/opt/jboss/wildfly/standalone/log
    - ./wildfly/standalone/lib:/opt/jboss/wildfly/standalone/lib
    depends_on:
    - appdb
    links:
    - appdb:wildflydbhost
    
  appdb:
    build:
      context: ./mysql
    networks: 
      ntrestapi:
        ipv4_address: 192.22.0.3
    image: wildfly-db
    container_name: wildfly-db
    environment:
      TZ: Europe/Rome
      MYSQL_IP: ::1
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_DATABASE: restapidemo
      MYSQL_USER: user
      MYSQL_PASSWORD: ma45lata
      MYSQL_ROOT_PASSWORD: kj7£fiU
    ports:
    - 3306:3306
    
  phpmyadmin:
    depends_on:
    - appdb
    networks: 
      ntrestapi:
        ipv4_address: 192.22.0.4
    image: phpmyadmin/phpmyadmin
    container_name: myadmin-wildfly
    restart: always
    environment:
      PMA_ARBITRARY: 1
    links:
    - appdb:wildflydb
    ports:
    - 8883:80