######################################
# Server properties
######################################
server:
  servlet:    context-path: /users-service

######################################
# Spring application properties
######################################
spring:
  profiles: 
    active: ${app.profile:testcase}
  application:
    name: bookmarks
# ==============================================================
# = Actuator Parameters
# ==============================================================
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,metrics,refresh,bus-refresh
        